name: BestKnownFor
favicon: null
layout_spectrum: 0.6208696810062975
typography_spectrum: 0.32248985138721764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4716637416277081
  lightness: 0.9232593760825694
  saturation: 0.2964392569847405
  rhythmicContrast: 0.9318857591133565
purpose: []
